# Generated by Django 5.2.4 on 2025-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
