# Generated by Django 5.1.4 on 2025-06-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(choices=[('GK', 'General Knowledge'), ('MV', 'Movies & TV Shows'), ('VG', 'Video Games'), ('MU', 'Music'), ('SC', 'Science & Nature'), ('HS', 'History & Culture'), ('IN', 'Internet & Pop Culture'), ('SP', 'Sports'), ('LT', 'Literature & Language'), ('LG', 'Logic & Riddles'), ('AnimeAnime', 'Anime'), ('CTCartoons', 'Cartoon')], default='GK', max_length=10),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
        ),
    ]
