# Generated by Django 5.2.4 on 2025-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_topic_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(choices=[('GK', 'General Knowledge'), ('MV', 'Movies & TV Shows'), ('VG', 'Video Games'), ('MU', 'Music'), ('SC', 'Science & Nature'), ('HS', 'History & Culture'), ('IN', 'Internet & Pop Culture'), ('SP', 'Sports'), ('LT', 'Literature & Language'), ('LG', 'Logic & Riddles'), ('AN', 'Anime'), ('CT', 'Cartoons')], default='GK', max_length=10),
        ),
    ]
